### ISSUE TITLE
Coverage plugins does not work when loading CSS

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manojjsm/js-test-driver#143]
```
What steps will reproduce the problem?
1. Load CSS via config file
2. Enable coverage
3. Run tests

What is the expected output? What do you see instead?
line 0:0 no viable alternative at character ''
line 0:0 no viable alternative at character ''

What version of the product are you using? On what operating system?
1.2.2 on OSX

The coverage module does not work if you include any CSS files. This could also 
be fixed with an extra exclude list for the coverage module itself. Which would 
help to not generate statistics for additional Libraries.
```

Original issue reported on code.google.com by `tobias.e...@gmail.com` on 4 Oct 2010 at 9:36

**Comment by GoogleCodeExporter** [comment]
```
Please include sample config.
```

Original comment by `corbinrs...@gmail.com` on 4 Oct 2010 at 4:44

**Comment by GoogleCodeExporter** [comment]
```
It didn't work with every CSS file I tried so far:

server: http://localhost:8888
plugin:
  - name: "coverage"
    jar: "plugins/coverage.jar"
    module: "com.google.jstestdriver.coverage.CoverageModule"

load:
  - ../src/Application/bundle/Resources/public/vendor/yui/cssreset/reset.css


line 0:0 no viable alternative at character ''
line 0:0 no viable alternative at character ''
line 0:0 no viable alternative at character ''
line 12:4 no viable alternative at input '{'

```

Original comment by `tobias.e...@gmail.com` on 12 Oct 2010 at 2:13

**Comment by GoogleCodeExporter** [comment]
```
the same problem... I've attached files: first with my configuration settings 
and second with stacktrace 
```

Original comment by `IgorNes...@gmail.com` on 15 Feb 2012 at 1:37

Attachments:
- [components.about.tests.conf](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-143/comment-3/components.about.tests.conf)
- [stacktrace.log](https://storage.googleapis.com/google-code-attachments/js-test-driver/issue-143/comment-3/stacktrace.log)

**Comment by GoogleCodeExporter** [comment]
```
Not sure, but shouldn't CSS file be provided using the serve: keyword:

server: http://localhost:8888
plugin:
  - name: "coverage"
    jar: "plugins/coverage.jar"
    module: "com.google.jstestdriver.coverage.CoverageModule"

serve:
  - ../src/Application/bundle/Resources/public/vendor/yui/cssreset/reset.css
```

Original comment by `IvDo...@gmail.com` on 13 Nov 2012 at 1:44
